window_padding_width 2
# font_size 11.0
# font_family      JetBrainsMono Nerd Font
# italic_font      auto
# bold_font        auto
# bold_italic_font auto
include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0
map kitty_mod+h launch --type=overlay --stdin-source=@screen_scrollback nvim -u NONE -i NONE -M -c 'normal G' -c 'colorscheme vim' -c 'map q :q!<CR>' -c 'set clipboard=unnamedplus laststatus=0 nospell syntax=' -
