return {}
-- return {
--   { import = "lazyvim.plugins.extras.lang.typescript" },
--   { import = "lazyvim.plugins.extras.lang.markdown" },
--   { import = "lazyvim.plugins.extras.lang.python" },
--   { import = "lazyvim.plugins.extras.lang.docker" },
--   { import = "lazyvim.plugins.extras.lang.go" },
--   { import = "lazyvim.plugins.extras.lang.rust" },
--   { import = "lazyvim.plugins.extras.lang.svelte" },
--   { import = "lazyvim.plugins.extras.lang.tailwind" },
--   -- { import = "lazyvim.plugins.extras.editor.snacks_picker" },
--   { import = "lazyvim.plugins.extras.editor.neo-tree" },
--   { import = "lazyvim.plugins.extras.coding.mini-surround" },
--   { import = "lazyvim.plugins.extras.formatting.prettier" },
--   { import = "lazyvim.plugins.extras.dap.core" },
-- }
